In [14]:
from numpy import matrix
from numpy import linalg

In [4]:
A = matrix([[1,2,3],[0,1,-1],[1,1,0]])
A

matrix([[ 1,  2,  3],
        [ 0,  1, -1],
        [ 1,  1,  0]])

In [8]:
A.T  #Traspuesta

matrix([[ 1,  0,  1],
        [ 2,  1,  1],
        [ 3, -1,  0]])

In [9]:
A.H  #Hermítica, traspuesta y conjugada

matrix([[ 1,  0,  1],
        [ 2,  1,  1],
        [ 3, -1,  0]])

In [15]:
linalg.det(A)

-4.0

In [16]:
e = linalg.eig(A)   #autovalores y autovectores

In [17]:
e[0]

array([-1.26953084+0.j        ,  1.63476542+0.69160123j,
        1.63476542-0.69160123j])

In [18]:
e[1]

matrix([[ 0.84265746+0.j        , -0.84993597+0.j        , -0.84993597-0.j        ],
        [-0.21711040+0.j        ,  0.27074166-0.27251781j,
          0.27074166+0.27251781j],
        [-0.49273876+0.j        , -0.36033109-0.01426038j,
         -0.36033109+0.01426038j]])